networks:
  medods-auth:
    external: true


services:

  postgresql:
    restart: always
    image: postgres:14
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr, csvlog"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgres/create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - 3333:5432
    networks:
      - medods-auth
    container_name: medods-auth-postgres

  app:
    image: medods-auth-app
    ports:
      - 8022:8020
    networks:
      - medods-auth
    depends_on:
      - postgresql
    container_name: medods-auth-app
    environment:
      JWT_SECRET: "jwt_secret_example"
      host_db: "medods-auth-postgres"
      port_db: "5432"
      user_db: "postgres"
      password_db: "postgres"
      dbname_db: "postgres"
      sslmode_db: "disable"
    command:  ["wait-for-it.sh", "medods-auth-postgres:5432", "--", "/app/bin"]